baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ICT pages'
theme = 'mainroad'

enableEmoji = true

[Params]
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  readmore = true # Show "Read more" button in list if true
  toc = true # Enable Table of Contents

[Params.sidebar]
  home = "right" # Configure layout for home page
  widgets = ["recent", "categories", "taglist"]

[markup.goldmark.renderer]
unsafe= true