baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ICT pages'
theme = 'mainroad'

enableEmoji = true

[Params]
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information

[Params.sidebar]
  home = "right" # Configure layout for home page
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
